name: learning
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.8
  pdfx: 2.6.0
  syncfusion_flutter_pdfviewer: 24.2.8
  reactive_forms: 17.0.1
  path_provider: 2.1.3
  extended_image: 8.2.1
  fpdart: 1.1.0
  logger: 2.3.0
  flutter_color: any
  get: 4.6.6
  win32: any
  badges: 3.1.2
  flutter_screenutil: 5.9.3
  step_progress_indicator: 1.0.2
  share_plus: 9.0.0
  fluttertoast: 8.2.6
  animate_do: 3.3.4
  connectivity_plus: 6.0.3
  carousel_slider: 5.0.0
  loading_animation_widget: 1.2.1
  infinite_scroll_pagination: 4.0.0
  gap: 3.0.1
  image_cropper: 7.0.0
  bloc: 8.1.4
  rflutter_alert: 2.0.7
  flutter_riverpod: 2.5.1
  awesome_dialog: 3.2.1
  modal_bottom_sheet: 3.0.0
  dio: 5.4.3+1
  toggle_switch: 2.3.0
  pin_code_fields: 8.0.1
  dots_indicator: ^3.0.0
  font_awesome_flutter: 10.7.0
  calendar_date_picker2: 1.0.3
  get_storage: 2.1.1
  shimmer: 3.0.0
  lottie: 3.1.2
  qr_code_scanner: 1.0.1
  intl: 0.19.0
  auto_size_text: 3.0.0
  animated_toggle_switch: 0.8.2
  google_fonts: 6.2.1
  flutter_svg: 2.0.10+1
  flex_color_scheme: 7.3.1
  audioplayers: 6.0.0
  crypto: 3.0.3
  file_picker: 8.0.3
  firebase_messaging: 15.0.0
  flutter_bloc: 8.1.5
  sqflite: 2.3.3+1
  flutter_widget_from_html: 0.15.0
  photo_view: 0.14.0
  get_it: 7.7.0
  image_picker: 1.1.2
  permission_handler: 11.3.1
  firebase_crashlytics: 4.0.0
  socket_io_client: 2.0.3+1
  provider: 6.1.2
  stop_watch_timer: 3.1.1
  textless: 6.6.6
  timeago: 3.6.1
  url_launcher: 6.3.0
  video_player: 2.8.6
  firebase_core: 3.0.0
  http: 1.2.1
  path: 1.9.0
  firebase_analytics: 11.0.0
  flutter_onboarding_slider: 1.0.11
  smooth_page_indicator: 1.1.0
  flutter_holo_date_picker: 1.1.3
  hand_signature: 3.0.3
  pinput: 4.0.0
  flutter_widget_from_html_core: any
  biometric_storage: ^5.0.1
  table_calendar: ^3.1.1
  flutter_staggered_grid_view: ^0.7.0
  local_auth: ^2.2.0
  flutter_screen_lock: ^9.1.0
  easy_stepper: ^0.8.5
  carousel_indicator: ^1.0.6
  multi_select_flutter: ^4.1.3
  animated_size_and_fade: ^4.0.0
  tuple: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  custom_lint: 0.6.4
  riverpod_lint: 2.3.10
  flutter_gen_runner: 5.5.0+1
  build_runner:
flutter:
  uses-material-design: true
  assets:
    - assets/base/
    - assets/onboard/
    - assets/Navigation_bar/